# Generated by Django 2.2.28 on 2023-03-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230324_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
