# Generated by Django 2.2.28 on 2023-03-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0003_delete_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('time', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
    ]
