# Generated by Django 2.2.28 on 2023-03-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='time',
            field=models.IntegerField(),
        ),
    ]
